name: Lint
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: 30 12 * * * # 30 minutes before Dependabot

permissions: write-all

jobs:
    bump:
        name: Bump dependencies
        if: startsWith(github.ref_name, 'dependabot/') != true
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Bump
              id: sync_types
              uses: RedGuy12/sync-types@v1.2.5

            - name: Commit
              id: commit
              uses: stefanzweifel/git-auto-commit-action@v4.16.0
              with:
                  commit_message: Bump dependencies
                  branch: ${{ github.head_ref }}

            - name: Comment
              run: |
                  body="<details><summary>Bumped dependencies</summary>${{ steps.sync_types.outputs.changes }}</details><details><summary>Requirement changes</summary>${{ steps.sync_types.outputs.sync }}</details>"
                  echo "$body" | gh api "repos/${{ github.repository }}/commits/${{ steps.commit.outputs.commit_sha }}/comments" -X POST -F body=-
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    format:
        name: Format
        if: startsWith(github.ref_name, 'dependabot/') != true
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Format
              run: npm run format

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@v4.16.0
              with:
                  commit_message: Format
                  branch: ${{ github.head_ref }}

    analyze:
        name: Analyze
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup CodeQL
              uses: github/codeql-action/init@v2.3.3
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Analyze
              uses: github/codeql-action/analyze@v2

    build:
        name: Build
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3.5.3
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.JS
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: "18.12.1"
                  cache: npm

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build
